name: Build and Push Image

on:
  push:
    branches: [main]
    paths:
      - "app/**"
      - "Dockerfile"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Hadolint (Dockerfile lint)
        uses: hadolint/hadolint-action@v3.5.0
        with:
          dockerfile: Dockerfile
        continue-on-error: true
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::119994407234:role/github-actions-deployment-role
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ecs-project-repo
          IMAGE_TAG: ${{ github.sha }}
        run: docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          version: v0.69.3
          image-ref: "${{ steps.login-ecr.outputs.registry }}/ecs-project-repo:${{ github.sha }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Push image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ecs-project-repo
          IMAGE_TAG: ${{ github.sha }}
        run: docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG