name: Terraform Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4
        with:
          role-to-assume: arn:aws:iam::119994407234:role/github-actions-deployment-role
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@1cf010d3c7aef302051ccdb68c14c5dc2efa34ef # v6
        with:
          tflint_version: latest

      - name: Run TFLint
        working-directory: infra
        run: |
          tflint --init
          tflint --recursive
        continue-on-error: true

      - name: Run Checkov IaC Scan
        uses: bridgecrewio/checkov-action@444c9db6fa75e2d9c19ebf1fde7322089be9009e # v12
        with:
          directory: infra
          framework: terraform
          soft_fail: true
          output_format: cli
        continue-on-error: true

      - name: Terraform Plan
        working-directory: infra
        run: terraform plan -out=tfplan

      - name: Upload plan
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: tfplan
          path: infra/tfplan

  terraform-apply:
    needs: terraform-plan
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4
        with:
          role-to-assume: arn:aws:iam::119994407234:role/github-actions-deployment-role
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Download plan
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: tfplan
          path: infra

      - name: Terraform Apply
        working-directory: infra
        run: terraform apply tfplan